### PR TITLE
Refer to the new primary OSPool CM (SOFTWARE-5005)

### PR DESCRIPTION
**Pull request by brianhlin**
We actually have two CMs but it's not clear how to handle fallback in
the case of extended cm-1 failure but not cause issues when there are
intermittent cm-1 failures. E.g. if cm-1 is down when making the token
request and we fall back to cm-2 but cm-1 is up for retrieving the
approved token, I suspect that the end-to-end process would fail

### CODE REVIEW

**Comment by matyasselmeci** [comment]
IIRC flock.opensciencegrid.org is a DNS alias for cm-1; in case of extended failure, can't we just make the switch in DNS?

**Comment by brianhlin** [comment]
It is but the alias in place is really just to ensure backwards compat so we should change the registry reference over

**Review by matyasselmeci — APPROVED** [review]

**Comment by brianhlin** [comment]
Actually before we merge this, it looks like the OSPool trust domain is still `flock.opensciencegrid.org`, which may mean that we have to revert the changes to `{RESOURCE,SOURCE}_POSTFIX`

**Comment by brianhlin** [comment]
@matyasselmeci says that the suffix doesn't have to line up with the trust domain so we should be in the clear

**Pull request merged**
